### ISSUE TITLE
How to migrate in bootatrap 4

### ISSUE THREAD

**Issue by aslam-shaikh** [adamnurdin01/bootsnav#11]
In bootatrap 4 classes are changed how to migrate it ..

**Comment by adamnurdin01** [comment]
sory for now bootsnav isn't support for bootstrap 4

**Comment by aslam-shaikh** [comment]
I just love ur navbars,
But now im shifting to bootstrap4
And navigation bar is my real problem.
You made bootsnav real quick..
Waiting 4 bootstrap 4's bootssnav

**Comment by Purus** [comment]
👍  Waiting for v4 :)

**Comment by razikallayi** [comment]
:+1: Waiting for v4 :)

**Comment by imagina** [comment]
Waiting for v4 too! Donate button!
