### ISSUE TITLE
Not working in Bootstrap-4 beta 

### ISSUE THREAD

**Issue by tawhidulkhan** [adamnurdin01/bootsnav#18]
I used Bootsnav menu in bootstrap 3.7 and now I use bootstrap-4 beta but bootsnav menu does not work

**Comment by adamnurdin01** [comment]
sory... for now bootsnav is not support for bootstrap 4

**Comment by Ataurr** [comment]
@adamnurdin01  Are you working with bootstrap 4?

**Comment by adamnurdin01** [comment]
no

**Comment by Ataurr** [comment]
Are you already working with "without framework" ?

Thanks

**Comment by adamnurdin01** [comment]
Not yet.. still in plannig... 
I will share in bootsnav if finished
